// Generated by CoffeeScript 1.4.0
var __slice = [].slice;

module.exports = (function() {
  var Bee, Hive, beehive;
  Hive = require('./hive');
  Bee = require('./bee');
  beehive = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args);
      return Object(result) === result ? result : child;
    })(Hive, args, function(){});
  };
  beehive.createBeehive = beehive.createHive = beehive;
  beehive.Hive = Hive;
  beehive.Bee = Bee;
  return beehive;
})();
